name: Deploy Glue Scripts to S3

on:
  push:
    branches:
      - Develop
    paths:
      - glue_scripts/**
  workflow_dispatch:

jobs:
  deploy-glue-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Validate Glue scripts
        run: |
          python -m py_compile glue_scripts/*.py

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-north-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Sync Glue scripts to S3
        run: |
          aws s3 sync glue_scripts/ s3://ci-cd-testing-citibike-7/glue_scripts/ --delete
